---
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: "spark-with-git-clone"
  namespace: default
spec:
  type: Python
  mode: cluster
  pythonVersion: "3"
  image: "gcr.io/spark-operator/spark-py:v3.1.1"
  imagePullPolicy: Always
  mainApplicationFile: local:///tmp/spark/pi.py
  sparkVersion: "3.1.1"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  volumes:
    - name: "spark-code"
      emptyDir: {}
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.1.1
    annotations:
      sidecar.istio.io/inject: “false”
    serviceAccount: spark
    volumeMounts:
      - name: "spark-code"
        mountPath: "/tmp/spark"
    initContainers:
    - name: "git-clone"
      image: "alpine/git"
      args:
          - clone
          - --single-branch
          - --
          - https://github.com/jenoOvchi/spark-config-example.git
          - /data
      volumeMounts:
      - mountPath: /data
        name: spark-code
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.1.1
    annotations:
      sidecar.istio.io/inject: “false”
    volumeMounts:
      - name: "spark-code"
        mountPath: "/tmp/spark"
    initContainers:
    - name: "git-clone"
      image: "alpine/git"
      args:
          - clone
          - --single-branch
          - --
          - https://github.com/jenoOvchi/spark-config-example.git
          - /data
      volumeMounts:
      - mountPath: /data
        name: spark-code
