apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark
  namespace: default
rules:
  - verbs:
      - get
      - list
    apiGroups:
      - ''
    resources:
      - secrets
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - services
      - persistentvolumeclaims
      - pods
      - configmaps
